### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by redsn0w0**
Added the telegram group @BTCFork (https://telegram.me/BTCFork) for the people who uses telegram everyday.

### CODE REVIEW

**Comment by keepcalmandfork** [comment]
Concept ACK

Implementation wise, who is the group admin / is there one?  How would we go about adding one later?  Am only concerned about comm channel takeover.

Thanks for being the first external PR on the site!! :+1:

**Comment by redsn0w0** [comment]
Hi,
at the moment I'm the group admin but I can add many other admin (It's not a problem).
The telegram group can accept up to 5'000 members.

> Thanks for being the first external PR on the site!! 👍

You're welcome :).

**Comment by keepcalmandfork** [comment]
Minor detail and then I will merge:

Can you change "Join the telegram group at" to "Join us on Telegram at" (to be consistent w wording and capitalization)?

**Comment by ftrader** [comment]
Concept ACK from me as well, with some caveats.
1. IMO a desktop messaging app should not need to perform SMS-based phone verification during signup, esp. when this seems to be a weak point in the security.
2. I did not find any published signatures or checksums alongside their binary downloads, which throws up a red flag for me in terms of security.

I will personally avoid it for now, but support BTCForkers who wish use the service at their own risk.

**Comment by redsn0w0** [comment]
> Can you change "Join the telegram group at" to "Join us on Telegram at" (to be consistent w wording and capitalization)?

Yeah sure, I will fix asap.

> IMO a desktop messaging app should not need to perform SMS-based phone verification during signup, esp. when this seems to be a weak point in the security.

You can fix this with a simply second password (2FA) added to your 'account', the phone number will not be visible (only in these cases:http://telegram.wiki/tips:numbervisibility).

> I did not find any published signatures or checksums alongside their binary downloads, which throws up a red flag for me in terms of security.

I agree, they should add a md5 checksum or signature to the binary download (as an user suggested here : https://github.com/telegramdesktop/tdesktop/issues/2063).

I'm using it from about 3 years without any problem, just add a 2FA and you are safe.

**Comment by keepcalmandfork** [comment]
Cool, thanks.  Merged. Site takes up to an hour to update after merge, but it will occur automatically.

**Comment by redsn0w0** [comment]
> Cool, thanks. Merged. Site takes up to an hour to update after merge, but it will occur automatically.

Thanks, let me know when you will join so I can add you as Admin, also you @ftrader (if you want to join the Telegram group).

**Comment by ftrader** [comment]
Thanks Pangu, one of us will join on Telegram but I'm not yet sure who. Whoever it'll be will contact you about that.

**Comment by redsn0w0** [comment]
Perfect, my username on telegram is @redsn0w

**Comment by ftrader** [comment]
hi redsn0w,

keepcalmandfork and myself would like to delegate to hostfat on Telegram.
Could you please add him as admin on the group.

Thanks a lot.

**Comment by redsn0w0** [comment]
> hi redsn0w,
> 
> keepcalmandfork and myself would like to delegate to hostfat on Telegram.
> Could you please add him as admin on the group.
> 
> Thanks a lot.

Yeah no problem, @HostFat added as admin.

**Pull request merged**
