### PR TITLE
Feature/primitive i18n mockup

### PR DESCRIPTION
**Pull request by ftrader**
Manual mockup to see what it looks like with HostFat's Italian translation, and now some more translations (German, Spanish). Thanks to all translators who made this possible!

I noticed some issues on a smaller desktop with the top portion Nakamoto quote not being fully visible, because the big "We're forking" was being broken over two lines. There probably needs to be more space on top to accomodate such cases better.

### CODE REVIEW

**Comment by keepcalmandfork** [comment]
Cool, thanks for doing all this!  This is a larger PR so will take me a day or two to test & review.

If you haven't heard back within 5 days, ping me again :).  Thanks again!

**Comment by ftrader** [comment]
No worries. I'll work on getting the Polish translation added as well, since it's complete (thanks to user forkfork on Transifex).

Additional translations at this stage are just subfolders with adapted index.html files.

If anyone doesn't want to use Transifex for some reason, they could also submit a PR in this style quite easily.

Also, desperately missing at the moment are language selection / switching buttons at the top of the page.

**Comment by ftrader** [comment]
ping @keepcalmandfork :-)
will contact you on Slack, have a chat about what's happening with the site.

**Comment by ftrader** [comment]
This pull request will not be merged.

Work is underway on a much better solution. Join us on the Slack if you're interested in finding out more, or wait for the announcements on Reddit etc :-)

**Pull request closed without merging**
